---
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    - destroy
